config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :tests do
    member do
      post "into_rule_engine"
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :rule_sets

  resources :results
end

app/models/rule.rb
class Rule < ApplicationRecord
  belongs_to :rule_set, required: false
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  before_action :set_rule, only: [:show, :edit, :update, :destroy]

  # GET /rules
  # GET /rules.json
  def index
    @rules = Rule.all
  end

  # GET /rules/1
  # GET /rules/1.json
  def show
  end

  # GET /rules/new
  def new
    @rule = Rule.new
  end

  # GET /rules/1/edit
  def edit
  end

  # POST /rules
  # POST /rules.json
  def create
    @rule = Rule.new(rule_params)

    respond_to do |format|
      if @rule.save
        format.html { redirect_to @rule, notice: 'Rule was successfully created.' }
        format.json { render :show, status: :created, location: @rule }
      else
        format.html { render :new }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rules/1
  # PATCH/PUT /rules/1.json
  def update
    respond_to do |format|
      if @rule.update(rule_params)
        format.html { redirect_to @rule, notice: 'Rule was successfully updated.' }
        format.json { render :show, status: :ok, location: @rule }
      else
        format.html { render :edit }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1
  # DELETE /rules/1.json
  def destroy
    @rule.destroy
    respond_to do |format|
      format.html { redirect_to rules_url, notice: 'Rule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rule
      @rule = Rule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rule_params
      params.fetch(:rule, {})
    end
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/rules/_form.html.slim
= form_for(@rule, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @rule.errors.any?
    .alert.alert-danger.alert-dismissable role="alert"
      button.close type="button" data-dismiss="alert"
        span aria-hidden="true"
          | &times;
        span.sr-only
          | Close
      h4= "#{pluralize(@rule.errors.count,"error")} prohibited this rule from being saved:"
      ul
        - @rule.errors.full_messages.each do |msg|
          li= msg
  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

app/views/rules/edit.html.slim
.page-header
  = link_to rules_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @rule, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | rule

= render 'form'

app/views/rules/index.html.slim
.page-header
  = link_to new_rule_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  New Rule
  h1
    | Listing rules

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th
        th
        th
    tbody
      - @rules.each do | rule |
        tr
          td
            = link_to 'Show', rule
          td
            = link_to 'Edit', edit_rule_path(rule) 
          td
            = link_to 'Destroy', rule, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/rules/new.html.slim
.page-header
  = link_to rules_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | rule

= render 'form'

app/views/rules/show.html.slim
.page-header
  = link_to rules_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_rule_path(@rule), class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show rule
dl.dl-horizontal