config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :tests do
    member do
      post "into_rule_engine"
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :rule_sets

  resources :results
end

app/models/rule_set.rb
class RuleSet < ApplicationRecord
  has_many :rule_set_actions
  has_many :tasks, through: :rule_set_actions
  has_many :rules

  accepts_nested_attributes_for :rule_set_actions
  accepts_nested_attributes_for :rules
end

app/models/rule_set_action.rb
class RuleSetAction < ApplicationRecord
  belongs_to :task
  belongs_to :rule_set, required: false
end

app/controllers/rule_sets_controller.rb
class RuleSetsController < ApplicationController
  before_action :set_rule_set, only: [:show, :edit, :update, :destroy]

  # GET /rule_sets
  # GET /rule_sets.json
  def index
    @rule_sets = RuleSet.all
  end

  # GET /rule_sets/1
  # GET /rule_sets/1.json
  def show
  end

  # GET /rule_sets/new
  def new
    @rule_set = RuleSet.new
    @rule_set.rules.build
    @rule_set.rule_set_actions.build
  end

  # GET /rule_sets/1/edit
  def edit
  end

  # POST /rule_sets
  # POST /rule_sets.json
  def create
    @rule_set = RuleSet.new(rule_set_params)

    respond_to do |format|
      if @rule_set.save
        format.html { redirect_to @rule_set, notice: 'Rule set was successfully created.' }
        format.json { render :show, status: :created, location: @rule_set }
      else
        format.html { render :new }
        format.json { render json: @rule_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rule_sets/1
  # PATCH/PUT /rule_sets/1.json
  def update
    respond_to do |format|
      if @rule_set.update(rule_set_params)
        format.html { redirect_to @rule_set, notice: 'Rule set was successfully updated.' }
        format.json { render :show, status: :ok, location: @rule_set }
      else
        format.html { render :edit }
        format.json { render json: @rule_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rule_sets/1
  # DELETE /rule_sets/1.json
  def destroy
    @rule_set.destroy
    respond_to do |format|
      format.html { redirect_to rule_sets_url, notice: 'Rule set was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rule_set
      @rule_set = RuleSet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rule_set_params
      params.fetch(:rule_set, {}).permit(:name, :description, :priority, :operator, rules_attributes: [:id, :atom, :operator, :value], rule_set_actions_attributes: [:id, :task_id])
    end
end

app/helpers/rule_sets_helper.rb
module RuleSetsHelper
end

app/views/rule_sets/_form.html.slim
= form_for(@rule_set, html: { class: "form-horizontal", role: "form" }) do |f|
  - if @rule_set.errors.any?
    .alert.alert-danger.alert-dismissable role="alert"
      button.close type="button" data-dismiss="alert"
        span aria-hidden="true"
          | &times;
        span.sr-only
          | Close
      h4= "#{pluralize(@rule_set.errors.count,"error")} prohibited this rule_set from being saved:"
      ul
        - @rule_set.errors.full_messages.each do |msg|
          li= msg
  .form-group
    = f.label :name, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :name, class: "form-control"

  .form-group
    = f.label :description, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :description, class: "form-control"

  .form-group
    = f.label :operator, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :operator, class: "form-control"

  .form-group
    = f.label :priority, class: "col-sm-2 control-label"
    .col-sm-10
      = f.text_field :priority, class: "form-control"

  .form-group
    = f.label :rules, class: "col-sm-2 control-label"
    .col-sm-10.plus-container
      = f.fields_for :rules do |r|
        .form-group.plus-item
          .col-sm-4
            = r.text_field :atom, class: "form-control"
          .col-sm-2
            = r.text_field :operator, class: "form-control"
          .col-sm-4
            = r.text_field :value, class: "form-control"
          .col-sm-1
            .form-control style="border: none; box-shadow: none"
              span.glyphicon.glyphicon-plus
          .col-sm-1
            .form-control style="border: none; box-shadow: none"
              span.glyphicon.glyphicon-minus

  .form-group
    = f.label :rule_set_actions, "Actions", class: "col-sm-2 control-label"
    .col-sm-10.plus-container
      = f.fields_for :rule_set_actions do |r|
        .form-group.plus-item
          .col-sm-5
            = r.select :task_id, option_for_actions, {}, class: "form-control"
          .col-sm-1
            .form-control style="border: none; box-shadow: none"
              span.glyphicon.glyphicon-plus
          .col-sm-1
            .form-control style="border: none; box-shadow: none"
              span.glyphicon.glyphicon-minus
      

  .form-group
    .col-sm-offset-2.col-sm-10
      = f.submit class: "btn btn-primary"

coffee:
  $('body').on 'click', '.glyphicon-plus', ->
    $container = $(@).parents('.plus-container').first()
    nextItem = $container.find('.plus-item').length + 1
    html = $container.find('.plus-item')[0].outerHTML.replace(/\[0\]/g, "[" + nextItem + "]").replace(/_0_/g, "_" + nextItem + "_")
    $container.append(html)

  $('body').on 'click', '.glyphicon-minus', ->
    $(@).parents('.plus-item').remove()

app/views/rule_sets/edit.html.slim
.page-header
  = link_to rule_sets_path, class: 'btn btn-default' do
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to @rule_set, class: 'btn btn-primary' do
    span.glyphicon.glyphicon-info-sign
    |  Show 
  h1
    | Editing 
    | rule_set

= render 'form'

app/views/rule_sets/index.html.slim
.page-header
  = link_to new_rule_set_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    | New Rule set
  h1
    | Listing rule_sets

.table-responsive
  table.table.table-striped.table-bordered.table-hover
    thead
      tr
        th Name
        th Priority
        th Rules
        th Actions
        th colspan=3
    tbody
      - @rule_sets.each do | rule_set |
        tr
          td = rule_set.name
          td = rule_set.priority
          td = rule_set.rules.map{|rule| "#{rule.atom} #{rule.operator} #{rule.value}"}.join(" #{rule_set.operator} ")
          td 
            - rule_set.tasks.each_with_index do |a, index|
              p = "#{index+1}. #{a.name} #{a.content}"

          td
            = link_to 'Show', rule_set
          td
            = link_to 'Edit', edit_rule_set_path(rule_set) 
          td
            = link_to 'Destroy', rule_set, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/rule_sets/new.html.slim
.page-header
  = link_to rule_sets_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  h1
    | New 
    | rule_set

= render 'form'

app/views/rule_sets/show.html.slim
.page-header
  = link_to rule_sets_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Back 
  = link_to edit_rule_set_path(@rule_set), class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Edit 
  h1
    | Show rule_set
dl.dl-horizontal